#! /bin/bash

#generated by N. K. Schaefer, "that Chimp.gtf is a version of the CAT annotation I modified to sort in a way that Cellranger was okay with it and make sure transcript IDs were unique"

kb ref \
--workflow standard \
-i kb_Chimp.idx \
-g kb_Chimp.t2g \
-f1 kb_Chimp.fa \
/wynton/group/pollen/genomes/cellranger/Chimp_HAL/fasta/genome.fa \
/wynton/group/pollen/nathan/annotations/Chimp.gtf
